=== RamonFernando/Curso_DAW_2015_2018/FPGS DESARROLLO DE APLICACIONES WEB/LENGUAJE DE MARCAS/TEMA 3 XSD/ExamenLM.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.iessonferrer.net/Ramon"
elementFormDefault="qualified">
<xs:element name="asseguranca_cotxe">
	<xs:complexType>
		<xs:sequence> 
			<xs:element name="asseguranca" maxOccours="6">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="asseguradora" type="xs:string"/>
						<xs:element name="geocobertura" type="tipo"/>
							<xs:element name="cobrament">
								<xs:complexType>
									<xs:all>									
										<xs:element name="financament" type="xs:string"/>
										<xs:element name="mensualitat" type="xs:decimal"/>
										<xs:element name="mensualitativa" type="xs:decimal"/>
										<xs:element name="anual" type="xs:integer"/>
									</xs:all>
									<xs:attribute name="moneda" type="Fijo"/>
									<xs:attribute name="aplicable" type="Tipo1"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="promocions">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="descompteonline" type="xs:integer"/>	
										<xs:element name="descompteedat">
										  <xs:complexType>
											<xs:simpleContent>
											  <xs:extension base="xs:string">
												<xs:attribute name="edat" type="xs:integer"/>
											  </xs:extension>
											</xs:simpleContent>
										  </xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="permetMensual" type="xs:string"/>
								</xs:complexType>
							

							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:ID"/>
						<xs:attribute name="denominacio" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	  <xs:simpleType name="tipo">
		<xs:restriction base="xs:string">
		  <xs:enumeration value="EspaÃ±ola"/>
		  <xs:enumeration value="Europea"/>
		  <xs:enumeration value="Mundial"/>
		</xs:restriction>
	  </xs:simpleType>
	<xs:simpleType name="tipo1">
		<xs:restriction base="nouClient">
		  <xs:enumeration value="Todos"/>
		 </xs:restriction>
	  </xs:simpleType>

	<xs:simpleType name="Fijo">
		<xs:restriction base="xs:string">
		  <xs:enumeration value="Euro"/>
		  </xs:restriction>
	  </xs:simpleType>
</xs:element>
</xs:schema>

=== RamonFernando/Curso_DAW_2015_2018/FPGS DESARROLLO DE APLICACIONES WEB/LENGUAJE DE MARCAS/TEMA 3 XSD/ExamenLM.xml
<?xml version="1.0" encoding="UTF-8"?>
<asseguranca_cotxe
xmlns="http://www.iessonferrer.net/Ramon"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.iessonferrer.net/Ramon ExamenLM.xsd">
  <asseguranca id="a1" denominacio="AXA AutoFlexible">
          <asseguradora>AXA</asseguradora>
          <geocobertura>Europea</geocobertura>
          <cobrament moneda="Euro" permetMensual="Si">
              <financament>12mesos</financament>
              <mensualitat>8.41</mensualitat>
              <mensualitativa>9.91</mensualitativa>
              <anual>123</anual>
          </cobrament>
          <promocions aplicable="tothom">
              <descompteonline>10</descompteonline>
          </promocions>
    </asseguranca>
    
    <asseguranca id="a2" denominacio="Fenix Seguros PolizaPlus">
          <asseguradora>FenixDirecto</asseguradora>
          <geocobertura>Europea</geocobertura>
          <cobrament moneda="Euro" permetMensual="Si">
              <financament>12mesos</financament>
              <mensualitat>12.43</mensualitat>
              <mensualitativa>14.67</mensualitativa>
              <anual>182</anual>
          </cobrament>
          <promocions aplicable="tothom">
              <descompteedat edat="35">20</descompteedat>
          </promocions>
    </asseguranca>
    
    <asseguranca id="a3" denominacio="Balumba SinAsistencia">
          <asseguradora>Balumba.es</asseguradora>
          <geocobertura>Espanyola</geocobertura>
          <cobrament moneda="Euro" permetMensual="No">
              <financament>1any</financament>
              <anual>192</anual>
          </cobrament>
          <promocions aplicable="nouClient"></promocions>
    </asseguranca>
    
    <asseguranca id="a4" denominacio="FenixDirecto + PackSeguridad">
          <asseguradora>FenixDirecto</asseguradora>
          <geocobertura>Europea</geocobertura>
          <cobrament moneda="Euro" permetMensual="Si">
              <financament>12mesos</financament>
              <mensualitat>13.25</mensualitat>
              <mensualitativa>15.64</mensualitativa>
              <anual>194</anual>
          </cobrament>
          <promocions aplicable="tothom">
              <descompteonline>15</descompteonline>
          </promocions>
    </asseguranca>
    
    <asseguranca id="a5" denominacio="Pelayo Tarifa Nocturna">
          <asseguradora>Pelayo</asseguradora>
          <geocobertura>Espanyola</geocobertura>
          <cobrament moneda="Euro" permetMensual="No">
              <financament>1any</financament>
              <anual>212</anual>
          </cobrament>
          <promocions aplicable="nouClient">
              <descompteonline>10</descompteonline>
              <descompteedat edat="40">25</descompteedat>
          </promocions>
    </asseguranca>
    
    <asseguranca id="a6" denominacio="Catalana Occidente">
          <asseguradora>Catalana Occidente</asseguradora>
          <geocobertura>Espanyola</geocobertura>
          <cobrament moneda="Euro" permetMensual="Si">
              <financament>6mesos</financament>
              <mensualitat>58.63</mensualitat>
              <mensualitativa>69.53</mensualitativa>
              <anual>429</anual>
          </cobrament>
          <promocions aplicable="nouClient"></promocions>
    </asseguranca>
</asseguranca_cotxe>
